#176 Keras CNN Model added
srimani-programmer/Breast-Cancer-Predictor pull request #184
Opened 2022-03-05 01:20 UTC by shreya024

I have added a Keras CNN Model with 94.9% accuracy

2022-03-06 14:56 UTC, srimani-programmer requested changes
@shreya024 Please do the requested Changes and Commit and I'll review the Same. Thanks for your Contribution. Your Code is good work but needs some improvements according to the application flow.

2022-03-06 14:56 UTC, srimani-programmer commented on Model/bc_prediction_cnn.py
> +dataset=pd.read_csv('../Dataset/Cleaned_data_Breast_Cancer.csv')
@shreya024 Try to customize this model which can able to read the data from the Flask Application and predict the result using your Model.

2022-03-06 14:56 UTC, srimani-programmer commented on Model/bc_prediction_cnn.py
> +results = model.evaluate(X_test, y_test)
What are you doing with these results? Please make sure to write proper comments and do the appropriate changes as well.

2022-03-06 16:10 UTC, shreya024 commented on Model/bc_prediction_cnn.py
> +dataset=pd.read_csv('../Dataset/Cleaned_data_Breast_Cancer.csv')
Hey @srimani-programmer I actually do not know Flask...so if you could provide a code example/resource...I would love to learn and then make the requested changes.

2022-03-06 16:10 UTC, shreya024 commented on Model/bc_prediction_cnn.py
> +results = model.evaluate(X_test, y_test)
Okay sure

2022-03-31 01:23 UTC, shreya024 commented
@srimani-programmer I have deployed the CNN model using Flask. Kindly check now

2022-04-03 05:19 UTC, shreya024 commented
> @srimani-programmer @freny24  I have deployed the CNN model using Flask. Kindly check now

2022-04-09 06:45 UTC, srimani-programmer commented
@freny24 Could you tag the appropriate level label to this PR and merge it as I reviewed the code everything seems perfect.

2022-04-09 06:55 UTC, shreya024 commented
> @freny24 Could you tag the appropriate level label to this PR and merge it as I reviewed the code everything seems perfect.

Thank you for reviewing. Appreciate if you could make it a level 3 as I have made the CNN model and customized it as well for the Flask Application

2022-04-09 08:17 UTC, merged