MODEL_COMPARISION AND RESULTS
srimani-programmer/Breast-Cancer-Predictor pull request #19
Opened 2021-01-07 14:34 UTC by spursbyte

this is in lieu with issue no #14. kindly review the notebook and the readme file.

2021-01-08 04:02 UTC, srimani-programmer requested changes
@spursbyte You made a lot of mistakes in this PR
1. You send the PR to the base branch but you need to send it to the New_Pipeline branch
2. You uploaded the Notebook file. But we don't need a notebook file I already intimated to develop two different scripts.
Follow up the above mistakes then we will intimate further more.

2021-01-10 16:10 UTC, spursbyte commented
I HAVE UPDATED THE REQUIRED FILES AND DELETED THE NOTEBOOK. I HAVE UPDATED THE README FOR MY PR ACCORDINGLY KINDLY REVIEW.

2021-01-13 05:51 UTC, srimani-programmer requested changes
Do the requested changes.

2021-01-13 05:51 UTC, srimani-programmer commented on breast_cancer_model_exploration/breast_cancer_ann.py
> +# Importing libraries
@spursbyte Add your models file into the models folder which is available in the project.

2021-01-13 05:51 UTC, srimani-programmer commented on breast_cancer_model_exploration/gridsearch.py
> +import numpy as np
Add this one to the models folder.

2021-01-14 15:28 UTC, spursbyte commented
done with the cahnges kindly review..one more thing i have also the readme file of the model in the model directory should i keep it or delete it?

2021-01-15 14:09 UTC, srimani-programmer requested changes

2021-01-15 14:09 UTC, srimani-programmer commented on Model/gridsearch.py
> +
@spursbyte remove extra line just add one it's enough

2021-01-15 14:09 UTC, srimani-programmer commented on Model/breast_cancer_ann.py
> +
@spursbyte remove extra line.

2021-01-15 14:20 UTC, spursbyte commented on Model/breast_cancer_ann.py
> +
Ok on it

2021-01-15 15:51 UTC, spursbyte commented on Model/breast_cancer_ann.py
> +
@srimani-programmer  DONE WITH TTHE CHANGES

2021-01-15 15:51 UTC, spursbyte commented on Model/readme.md
> +### VARIOUS CLASSIFICATION MODEL COMPARISION AND CHOOSING THE BEST ONE.
DONE WITH THE CHANGES

2021-01-15 15:52 UTC, spursbyte commented on Model/gridsearch.py
> +
DIME WITH THE CHANGES

2021-02-14 11:12 UTC, srimani-programmer approved these changes

2021-02-14 11:13 UTC, merged