Added breast cancer classifier
srimani-programmer/Breast-Cancer-Predictor pull request #33
Opened 2021-01-13 18:49 UTC by ckmganesh

Fixes #10

Added the breast cancer classifier as described by the issue. The accuracy of the model can also be seen when the script is run

2021-01-13 19:14 UTC, srimani-programmer requested changes
Please add your model inside models folder.

2021-01-13 19:14 UTC, srimani-programmer commented on randomforest_classifier.py
> +print("Accuracy :",(cm[0][0]+cm[1][1])/Y_pred.shape[0])
@ckmganesh Add new line at the end.

2021-01-13 19:15 UTC, srimani-programmer commented
@ckmganesh please make your PR to New_Pipeline Branch.

2021-01-13 20:56 UTC, ckmganesh commented
Check the other PR. Ignore this one. All the required changes are done on that PR. Please check it out

2021-01-15 14:05 UTC, srimani-programmer requested changes
Something went worng with this PR. Please make a new PR. It is saying unknown PR.

2021-01-15 14:10 UTC, ckmganesh commented
I've created another PR. I already mentioned it before. Check #34 .
I'm closing this PR

2021-01-15 14:10 UTC, closed without merging