Added all the changes for cancer classifier
srimani-programmer/Breast-Cancer-Predictor pull request #34
Opened 2021-01-13 20:55 UTC by ckmganesh

Fixes #10 
Added all the changes suggested and also changed the branch for PR

2021-01-21 13:36 UTC, srimani-programmer requested changes

2021-01-21 13:36 UTC, srimani-programmer commented on Model/randomforest_cancerclassifier.py
> +print()
@ckmganesh please add the extra line at the end of the file.

2021-01-22 12:58 UTC, ckmganesh commented on Model/randomforest_cancerclassifier.py
> +print()
I don't understand.should I just add a line?

2021-02-14 11:12 UTC, srimani-programmer requested changes

2021-02-14 11:12 UTC, srimani-programmer commented on Model/randomforest_cancerclassifier.py
> +print()
@ckmganesh please remove the extra print statement and just add an empty line.

2021-03-19 07:14 UTC, honey2158 commented
I have also written a code using 3 different models and got a good accuracy where should i upload my code. As I am new to open source and don't know much about github can anyone help me with it.

2021-06-02 14:33 UTC, closed without merging