Added navbar and header
srimani-programmer/Breast-Cancer-Predictor pull request #58
Opened 2021-03-12 08:29 UTC by Bhavik-Ardeshna

#9 #7 
![Screenshot from 2021-03-12 13-57-46](https://user-images.githubusercontent.com/58507059/110913444-2d39bd80-833b-11eb-8da6-4e9d2da87650.png)

2021-03-12 16:29 UTC, srimani-programmer commented
@Bhavik-Ardeshna Did you make this PR AS part of GSSOC?

2021-03-12 16:43 UTC, Bhavik-Ardeshna commented
yes

On Fri, Mar 12, 2021, 10:00 PM Sri Manikanta Palakollu <
***@***.***> wrote:

> @Bhavik-Ardeshna <https://github.com/Bhavik-Ardeshna> Did you make this
> PR AS part of GSSOC?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/srimani-programmer/Breast-Cancer-Predictor/pull/58#issuecomment-797602847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN6L6M4OZE3EL52YC3CRZATTDI6RPANCNFSM4ZB2PBPQ>
> .
>

2021-03-15 17:32 UTC, Bhavik-Ardeshna commented
I think this PR is ready to merge please review :)

2021-03-29 14:04 UTC, srimani-programmer requested changes
@Bhavik-Ardeshna there are a lot of spam changes in the PR. please don't do that. If you want to contribute to this project please read the guidelines properly.

2021-03-29 14:04 UTC, srimani-programmer commented on implementation.py
> -	# Feature Scaling
@Bhavik-Ardeshna Why there is an unnecessary spaces although the file

2021-03-29 14:04 UTC, srimani-programmer commented on random_forest.py
> -dataset = pd.read_csv('Breast Cancer Data.csv')
@Bhavik-Ardeshna why you are trying to change the filename.

2021-04-17 13:51 UTC, srimani-programmer commented
@Bhavik-Ardeshna Your code is conflicting with the project code base. please read the guidelines properly and make new PR.

2021-04-17 13:51 UTC, closed without merging