Auto scroll added
srimani-programmer/Breast-Cancer-Predictor pull request #97
Opened 2021-03-24 19:10 UTC by DEEPIKA-SUK

![Screenshot (128)](https://user-images.githubusercontent.com/64724039/112369225-f59b2000-8d01-11eb-8ec1-663d35d0b0e1.png)

2021-03-24 19:10 UTC, DEEPIKA-SUK commented
Issue:#89
@srimani-programmer Kindly review my PR.

2021-04-02 09:39 UTC, srimani-programmer requested changes
@DEEPIKA-SUK did you raised an issue for this PR. if yes please provide the issue number. If not then please raise an issue and let me know. I'll merge this code.

2021-04-02 10:43 UTC, DEEPIKA-SUK commented
> @DEEPIKA-SUK did you raised an issue for this PR. if yes please provide the issue number. If not then please raise an issue and let me know. I'll merge this code.

The issue #89 that I opened was consisting of two parts one improving the UI for "tumor.html" and second adding auto-scroll ( scroll to the top of the page) on the homepage. Since all the changes were needed to be made in "New-pipeline" branch, I could not find "Tumor.html" page anywhere in that branch so I did only the second part of the issue that is added scroll-to-top button.

2021-04-17 04:56 UTC, srimani-programmer approved these changes

2021-04-17 04:57 UTC, merged